name: format
on:
  push:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
    
permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Format files
        run: |
          npx prettier --write '**/*.{md,yml}'
      - name: Sync to `main`
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Our git status is not clean. Checking in the following files:";
            echo "$(git status --porcelain)";
          fi
