name: format
on:
  push:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
    
permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'joshblack/awesome-a11y' }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Update Table of Contents
        run: |
          npx doctoc --title '## Table of Contents' README.md
      - name: Format files
        run: |
          npx prettier --write '**/*.md'
      - name: Sync to `main`
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Our git status is not clean. Checking in the following files:";
            echo "$(git status --porcelain)";

            git config --global credential.helper 'cache --timeout=120'
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"

            git remote set-url origin "https://github.com/joshblack/awesome-a11y.git"
            git checkout main
            git add -A
            git commit -m "chore(project): format files"
            git push
          fi
